### ISSUE TITLE
minor nit re blank lines surrounding vsync

### ISSUE THREAD

**Issue by michielboland** [randyrossi/vicii-kawari#15]
Kawari version 1.5 (mini)

Some nit pickings regarding the vertical blanking/vertical sync generation.

The VIC-II does this, more or less:
 * normal display
 * one blank line (raster 13 NTSC, raster 300 PAL)
 * three vertical equalization lines (six half-lines) (14-16 NTSC, 301-303 PAL)
 * three vertical synchronization lines (17-19 NTSC, 304-306 PAL)
 * three vertical equalization lines (20-22 NTS, 307-309 PAL)
 * one blank line (23 NTSC, 310 PAL)
 * normal display

The Kawari appears to skip the second blank line.
Also the blank line that it does generate has color burst for some reason.
Finally the last vertical equalization line (22 NTSC, 309 PAL) also has a color burst, which is also not present on a real VIC-II. (And probably illegal according to PAL/NTSC standards, but VIC-II does not adhere to these anyway. :) )

Scope captures (NTSC, PAL is similar)

![kawari_ntsc_raster_14](https://user-images.githubusercontent.com/4216126/206028716-fdb32bb5-729f-4eaa-8141-305443d83f36.png)

kawari raster 14

![board6_raster_14](https://user-images.githubusercontent.com/4216126/206028770-36b2375e-b2ee-49ff-abc3-c62278bef150.png)

6567R8 raster 14

![kawari_ntsc_raster_23](https://user-images.githubusercontent.com/4216126/206028834-4e955dbf-a8d4-457b-8333-e649ebcff5c0.png)

kawari raster 23

![board6_raster_23](https://user-images.githubusercontent.com/4216126/206028862-272c0b52-f15f-4c4e-9c10-4b562e8520cd.png)

6567R8 raster 23

**Comment by randyrossi** [comment]
Thanks.  I'm trying to fix these issues in v1.12 of the firmware.
